### ISSUE TITLE
Difference with Repository of nwojke/deep_sort.git

### ISSUE THREAD

**Issue by bitzy** [oylz/DS#2]
Hi, 

I need to re-implement the original Deepsort Code by  C/C++ .  Then I ran your DS code and found that the tracking result was very different from the original Deepsort. There are many big rectangles in the 'frame' window, which will not happen in the original Deepsort's result. Could you tell me why this happened?

**Comment by oylz** [comment]
It’s using hog feature default. But the Tensorflow feature has coding(under deepsort/FeatureGetter/).I will add the cpp model(which is translated from python model)
